/*
 * Vultiserver API
 *
 * TSS (Threshold Signature Scheme) server for keygen, keysign, and reshare operations supporting ECDSA, EdDSA, and MLDSA via GG20 and DKLS protocols.  Vultiserver runs an Echo HTTP server and an asynq worker for async TSS operations backed by Redis. Most mutating endpoints enqueue an async task and return immediately. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchReshareRequest {
    /// Existing vault public key
    #[serde(rename = "public_key")]
    pub public_key: String,
    /// Unique session identifier (UUID)
    #[serde(rename = "session_id")]
    pub session_id: uuid::Uuid,
    /// 32-byte hex-encoded encryption key
    #[serde(rename = "hex_encryption_key")]
    pub hex_encryption_key: String,
    /// Local TSS party identifier
    #[serde(rename = "local_party_id", skip_serializing_if = "Option::is_none")]
    pub local_party_id: Option<String>,
    /// Encryption password for the vault
    #[serde(rename = "encryption_password")]
    pub encryption_password: String,
    /// Email address for vault backup delivery
    #[serde(rename = "email")]
    pub email: String,
    /// List of party IDs from the previous share set
    #[serde(rename = "old_parties")]
    pub old_parties: Vec<String>,
    /// List of protocols to reshare across
    #[serde(rename = "protocols")]
    pub protocols: Vec<String>,
}

impl BatchReshareRequest {
    pub fn new(public_key: String, session_id: uuid::Uuid, hex_encryption_key: String, encryption_password: String, email: String, old_parties: Vec<String>, protocols: Vec<String>) -> BatchReshareRequest {
        BatchReshareRequest {
            public_key,
            session_id,
            hex_encryption_key,
            local_party_id: None,
            encryption_password,
            email,
            old_parties,
            protocols,
        }
    }
}

