/*
 * Vultiserver API
 *
 * TSS (Threshold Signature Scheme) server for keygen, keysign, and reshare operations supporting ECDSA, EdDSA, and MLDSA via GG20 and DKLS protocols.  Vultiserver runs an Echo HTTP server and an asynq worker for async TSS operations backed by Redis. Most mutating endpoints enqueue an async task and return immediately. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeysignRequest {
    /// Public key identifying the vault backup file
    #[serde(rename = "public_key")]
    pub public_key: String,
    /// Hex-encoded messages to sign
    #[serde(rename = "messages")]
    pub messages: Vec<String>,
    /// Unique session identifier (UUID)
    #[serde(rename = "session")]
    pub session: uuid::Uuid,
    /// 32-byte hex-encoded encryption key
    #[serde(rename = "hex_encryption_key")]
    pub hex_encryption_key: String,
    /// BIP-32 derivation path for the signing key
    #[serde(rename = "derive_path")]
    pub derive_path: String,
    /// Use ECDSA signing (true) or EdDSA (false)
    #[serde(rename = "is_ecdsa", skip_serializing_if = "Option::is_none")]
    pub is_ecdsa: Option<bool>,
    /// Password to decrypt the vault backup
    #[serde(rename = "vault_password")]
    pub vault_password: String,
    /// Target blockchain (e.g. BTC, ETH)
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
    /// Use ML-DSA (post-quantum Dilithium) signing
    #[serde(rename = "mldsa", skip_serializing_if = "Option::is_none")]
    pub mldsa: Option<bool>,
}

impl KeysignRequest {
    pub fn new(public_key: String, messages: Vec<String>, session: uuid::Uuid, hex_encryption_key: String, derive_path: String, vault_password: String) -> KeysignRequest {
        KeysignRequest {
            public_key,
            messages,
            session,
            hex_encryption_key,
            derive_path,
            is_ecdsa: None,
            vault_password,
            chain: None,
            mldsa: None,
        }
    }
}

