/*
 * Vultiserver API
 *
 * TSS (Threshold Signature Scheme) server for keygen, keysign, and reshare operations supporting ECDSA, EdDSA, and MLDSA via GG20 and DKLS protocols.  Vultiserver runs an Echo HTTP server and an asynq worker for async TSS operations backed by Redis. Most mutating endpoints enqueue an async task and return immediately. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// LibType : TSS library/protocol type
/// TSS library/protocol type
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum LibType {
    GG20 = 0,
    DKLS = 1,
    KeyImport = 2,

}

impl std::fmt::Display for LibType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::GG20 => "0",
            Self::DKLS => "1",
            Self::KeyImport => "2",
        })
    }
}
impl Default for LibType {
    fn default() -> LibType {
        Self::GG20
    }
}

