/*
 * Vultiserver API
 *
 * TSS (Threshold Signature Scheme) server for keygen, keysign, and reshare operations supporting ECDSA, EdDSA, and MLDSA via GG20 and DKLS protocols.  Vultiserver runs an Echo HTTP server and an asynq worker for async TSS operations backed by Redis. Most mutating endpoints enqueue an async task and return immediately. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultResendRequest {
    /// 66-character hex-encoded ECDSA public key
    #[serde(rename = "public_key_ecdsa")]
    pub public_key_ecdsa: String,
    /// Vault encryption password
    #[serde(rename = "password")]
    pub password: String,
    /// Email address to resend the vault backup to
    #[serde(rename = "email")]
    pub email: String,
}

impl VaultResendRequest {
    pub fn new(public_key_ecdsa: String, password: String, email: String) -> VaultResendRequest {
        VaultResendRequest {
            public_key_ecdsa,
            password,
            email,
        }
    }
}

