/*
 * Vultiserver API
 *
 * TSS (Threshold Signature Scheme) server for keygen, keysign, and reshare operations supporting ECDSA, EdDSA, and MLDSA via GG20 and DKLS protocols.  Vultiserver runs an Echo HTTP server and an asynq worker for async TSS operations backed by Redis. Most mutating endpoints enqueue an async task and return immediately. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_derived_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDerivedPublicKeyError {
    Status400(models::Error),
    UnknownValue(serde_json::Value),
}


/// Derives a child public key from a parent public key using the given chain code and derivation path. Supports both ECDSA and EdDSA curves. 
pub async fn get_derived_public_key(configuration: &configuration::Configuration, public_key: &str, hex_chain_code: &str, derive_path: &str, is_ed_dsa: Option<bool>) -> Result<String, Error<GetDerivedPublicKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_public_key = public_key;
    let p_query_hex_chain_code = hex_chain_code;
    let p_query_derive_path = derive_path;
    let p_query_is_ed_dsa = is_ed_dsa;

    let uri_str = format!("{}/getDerivedPublicKey", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("publicKey", &p_query_public_key.to_string())]);
    req_builder = req_builder.query(&[("hexChainCode", &p_query_hex_chain_code.to_string())]);
    req_builder = req_builder.query(&[("derivePath", &p_query_derive_path.to_string())]);
    if let Some(ref param_value) = p_query_is_ed_dsa {
        req_builder = req_builder.query(&[("isEdDSA", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDerivedPublicKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

